# Linear Regression

# High-Level Recipe for Supervised Learning

- Summary
  - Supervised Learning is the process of associating a number of features ($X$) to an outcome of interest ($Y$) using a function ${f}$ as the connector: $y = f(x)$. To achieve this association this type of learning needs components...
- Components
  - Loss (i.e., Error) Function
    - This function measures how far our predictions are from our labels (i.e. truth)
    - This is what we're learning to minimze (i.e., optimize)
  - Relationship
    - We have a plethora of theoretical relationships to choose from (e.g., linear regression, xgboost, deep learning) all with their own pros and cons.
    - We choose one of these ideas to move forward with.
  - Model (Realization of the Relationship)
    - This function represents the model theory, so for example to bring the idea of linear regression to life we need a function in the following format: $f(x) = w_0 + w_1x_1 + w_2x_2 = y$
  - Optimization Algorithm
    - This algorithm modifies model function to minimize the magnitude of the error function by constantly adjusting the model function's weights.
  - Data Splits
    - We split our entire data into: training, valid, and test
    - The process of learning is done on the training data, validation is used for evaluation during training process and/or after to understand how our model would perform on unseen data
    - The test set is final check, its the dataset that the model function never sees until the last step. Its the true test to assess how we our model function performs
  - Evaluation of Model Function
    - We use a number of metrics to assess how our trained model function performs

# How to Choose a Model?

<img src="images/plot-1.png" width="500"/>

- We trained several models of varying complexity on a dataset and plotted their training (grey) and test (red) errors.
- As model complexity increases (orange → blue → green), training error decreases, but test error follows a U-shape—initially dropping, then rising—indicating underfitting (orange) and overfitting (green).
- This example illustrates an important attribute of models: **bias-variance tradeoff**

## Bias-Variance Tradeoff

- In the above example, we calculated test error using **empirical mean squared error (MSE)**:
$$\frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{f}(x_i))^2$$
- This quantifies how far off we are for a single process (i.e., train on a single train set then evaluate on a single test set)
- Now, let's say we sampled another dataset and/or trained slightly differently, we'd get a different result, so we can take this one step further and try to generalize this behavior
$$E[(y_0 - \hat{f}(x_0))^2]$$
- This is the **expected test MSE at $x_0$**, and refers to the test MSE that we would obtain if we repeatedly estimated $f$ using a large number of training sets, and tested each at $x_0$. You can think of it as the center of mass error for this specific point $x_0$ across infinite processes
- We focus on a single $x_0$ because model error (bias, variance, noise) can vary across different x-values (i.e. input space). Analyzing a single point helps us understand model behavior locally. To generalize, we take the expectation over the distribution of all possible input points $x$.
- Now then, let's understand what factors are at play when calculating our error at $x_0$ by decomposing this formula
$$E[(y_0 - \hat{f}(x_0))^2] = $$
$$E[(y_0 - \hat{f}(x_0))^2] = {\color{red}(f(x_0) - E[\hat{f}(x_0)])^2} + {\color{orange}E[(\hat{f}(x_0) - E[\hat{f}(x_0)])^2]} + {\color{green}E[\epsilon^2]}$$
$$E[(y_0 - \hat{f}(x_0))^2] = {\color{red}Bias(\hat{f}(x_0))^2} + {\color{orange}Var(\hat{f}(x_0))} + {\color{green}Var(\epsilon)}$$
- Interpretation
  - Bias: How far the average model prediction is from the true value at $x_0$
  - Variance: How much the model predictions vary across different datasets at $x_0$
  - $\epsilon$: random error that our function cannot capture

# Why Linear Regression?

- easy interpretation
- cheap to train the model
- less likely to overfit to data

# Linear Regression Methodology

## The Supervised Learning Recipe Applied to Linear Regression

- Error Function
  - Residual Sum of Squares: $\sum_{i=1}^{n}(y_i - \hat{f}(x_i))^2$
- Relationship
  - Linear
- Model
  - $\hat{f}(x) = w_0 + w^T*x$
- Optimization Algorithm
  - Maximum Likelihood Estimator

## Maximum Likelihood Estimator (MLE) for Linear Regression

- The purpose of MLE is to identify the characteristics (e.g., mean and variance of a normal distribution) of a known distribution given observed data (i.e. a random variable)
- Process
  1. Normal Distribution formula
    - $pr(x|\mu, \sigma) = \frac{1}{\sqrt{2\pi\sigma}}e^{-(x-\mu)^2/2\sigma^2}$
      - $x$: is the value for which the probability density is being calculated.
      - $\mu$: is the mean (average) of the distribution. 
      - $\sigma$: is the standard deviation of the distribution, which determines the spread of the curve. 
  2. Likelihood of the Normal Distribution formula
    - $L(\mu, \sigma|x) = \frac{1}{\sqrt{2\pi\sigma}}e^{-(x-\mu)^2/2\sigma^2}$
      - Identify the $\mu$ and $\sigma$ given the data
  3. Calculate the likelihood for every single $x_i$ in the random variable $X$, which is the product of the individual likelihoods, since we assume independent and identitically distributed (iid)
    - $L(\mu,\sigma|x_i) = \prod_{i=1}^{n}\frac{1}{\sqrt{2\pi\sigma}}e^{-(x_i-\mu)^2/2\sigma^2}$ 
    - We can identify the optimal $\mu$ and $\sigma$ that maximizes this expression by taking the gradient (i.e., derivative of multiple variables) of $\mu$ and $\sigma$ independently
  4. Convert Likelihood to Negative Log Likelihood (NLL)
    - -$\sum_{i=1}^{n}log(L(\mu,\sigma|x_i)) = -\frac{n}{2}log(2\pi\sigma^2) - \frac{1}{2\sigma^2}\sum_{i=1}^{n}(x_i - \mu)^2$ 
    - The conversion makes calculation easier because...
      - its easier to take derivatives with log
      - the negative means we want the values that minimizes this expression instead (which are the same values if we maximized) and many optimization software packages are designed to find the minima of functions, rather than maxima
  5. How NLL fits into Linear Regression
  - This is the true relationship between our label and prediction for the *i*th observation: $y_i = w_0 + w^T*x_i + \epsilon_i$
    - $\epsilon_i$: irreducible error for the *ith* observation, meaning this is the information that our model **cannot** capture
  - We can rewrite the above relationship as this: $\epsilon_i = y_i - (w_0 + w^T*x_i)$
    - This is the difference between our label and prediction for the *i*th observation
  - For every x-value, we want to predict mean value of all the associated y's, so our normal distribution looks like:
  -  $pr(y|w_0 + w^T*x, \sigma) = \frac{1}{\sqrt{2\pi\sigma}}e^{-(y-(w_0 + w^T*x))^2/2\sigma^2}$
     -  Below is graph representation of this probability distrubiton
     -  <img src="images/plot-3.png" width="500"/>
  -  Plugging in this difference into our NLL, we get
     -  $\sum_{i=1}^{n}log(L(w_0, w^T|x, y)) = -\frac{n}{2}log(2\pi\sigma^2) - \frac{1}{2\sigma^2}\sum_{i=1}^{n}(y_i-(w_0 + w^T*x_i))^2$ 
  -  We can ignore the variance part of the formula (assuming homoskedascity), since we're only concerned with predicting the mean y for every x value
     -  $\sum_{i=1}^{n}log(L(w_0, w^T|x, y)) = \sum_{i=1}^{n}(y_i-(w_0 + w^T*x_i))^2$
        -  This is just residual sum of squares (RSS)
  -  Through matrix operations, we can solve for both $w_0$ and $w^T$:
     -  $w^T = (X^{T}X)^{-1}X^Ty$
        -  for this operation to work, we must ensure that all features in X are independent of each other, meaning no feature is a variation of another (e.g., weight in kilograms and weight in pounds), the reason is because this makes it almost impossible to perform an inverse of the feature matrix, though modern packages have tried to work around this for an approximation of the resulting weights
     -  $w_0 = \frac{1}{n}\sum_{i=1}^{n}y_i$

# Evaluation Metrics

## Pearson

- Explanation
  - measures the linear relationship between two variables. Its value ranges between -1 and 1
- Formula
  - $r = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}
         {\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2} 
          \sqrt{\sum_{i=1}^n (y_i - \bar{y})^2}} = \frac{\text{Cov}(X, Y)}{\sigma_X \sigma_Y}$
  - x and y are the two populations to compare
  - $\bar{x}$ and $\bar{y}$ are the means of each population
- Advantage and Disadvantages
  - this is scale-invarient since any rescaling to either x or y will affect both numerator and denominator

## Spearman

- Explanation
  - measures the monotonic relationship between two variables using ranks rather than raw values. Like Pearson, its value ranges from -1 to 1
  - this is just measuring is the ranking in both population going in the same direction (1) or opposite (-1)
- Formula
  - $\rho = 1 - \frac{6 \sum_{i=1}^n d_i^2}{n(n^2 - 1)}$
  - Where:
    - $\rho$ is Spearman's rank correlation
    - $d_i$ is the difference between the ranks of each pair
    - $n$ is the number of data pairs
- Advantages and Disadvanteges
  - It is scale-invarient, since its only concerned with ranking and not variance
  - It can be used if we know the relationship is not linear

## $R^{2}$ Statistic

- Explanation
  - a proportion that measures how much variability in our outcome is accounted for by our features
- Formula
  - $TSS = \sum_{i=1}^{n}(y_i - \bar{y})^2$
    - measures the total variability in our outcome alone

  - $RSS = \sum_{i=1}^{n}(y_i - \hat{y_i})^2$
    - measures the total variability that remains unknown between the labels and predictions for our outcome
  
  - $R^{2} = \frac{TSS - RSS}{TSS}$
    - this can range from 0 and 1, where 1 means our regression model does a good job at predicting our outcome
- Advantages and Disadvantages
  - Can be useful to compare performance across different outcomes with different scales since this is a proportion
  - It is scale-variant, because if you rescale the predictions, then RSS changes, but TSS does not.

## Mean Squared Error (MSE)

- Explanation
  - the average error between our predictions and labels for our outcome
- Formula
  - $MSE = \frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y_i})^2$
- Advantages and Disadvantages
  - If further penalizing outlier predictions compared to predictions around the mean is important to consider then use this

## Mean Absolute Error (MAE)

- Explanation
  - the mean absolute error between our predictions and labels for our outcome
- Formula
  - $MAE = \frac{1}{n}\sum_{i=1}^{n}|y_i - \hat{y_i}|$
- Advantages and Disadvantages
  - if treating all predictions the same without further penalizing one over the other, then use this

## AIC and BIC

- Explanation
  - Both are used for model selection, especially when you're comparing multiple models. The smaller the value the better.
- Formulas
  - $AIC = 2k - ln(\hat{L})$
    - $k$ = # of features in model
    - $\hat{L}$ = likelihood value of the model = $\prod_{i=1}^{n}\frac{1}{\sqrt{2\pi\sigma}}e^{-(y_i-(w_0 + w^T * x_i))^2/2\sigma^2}$
  
  - $BIC = ln(n)k - 2ln(\hat{L})$
    - $k$ = # of features in model
    - $n$ = # of observations
    - $\hat{L}$ = likelihood value of the model = $\prod_{i=1}^{n}\frac{1}{\sqrt{2\pi\sigma}}e^{-(y_i-(w_0 + w^T * x_i))^2/2\sigma^2}$

# Practice

In [19]:
import numpy as np
import pandas as pd
import polars as pl
import pyarrow
from ISLP import load_data
import matplotlib.pyplot as plt
import matplotlib

In [20]:
# load dataset
Boston = load_data("Boston")
Boston = pl.from_pandas(Boston)
Boston.head()

shape: (5, 13)
┌─────────┬──────┬───────┬──────┬───┬─────┬─────────┬───────┬──────┐
│ crim    ┆ zn   ┆ indus ┆ chas ┆ … ┆ tax ┆ ptratio ┆ lstat ┆ medv │
│ ---     ┆ ---  ┆ ---   ┆ ---  ┆   ┆ --- ┆ ---     ┆ ---   ┆ ---  │
│ f64     ┆ f64  ┆ f64   ┆ i64  ┆   ┆ i64 ┆ f64     ┆ f64   ┆ f64  │
╞═════════╪══════╪═══════╪══════╪═══╪═════╪═════════╪═══════╪══════╡
│ 0.00632 ┆ 18.0 ┆ 2.31  ┆ 0    ┆ … ┆ 296 ┆ 15.3    ┆ 4.98  ┆ 24.0 │
│ 0.02731 ┆ 0.0  ┆ 7.07  ┆ 0    ┆ … ┆ 242 ┆ 17.8    ┆ 9.14  ┆ 21.6 │
│ 0.02729 ┆ 0.0  ┆ 7.07  ┆ 0    ┆ … ┆ 242 ┆ 17.8    ┆ 4.03  ┆ 34.7 │
│ 0.03237 ┆ 0.0  ┆ 2.18  ┆ 0    ┆ … ┆ 222 ┆ 18.7    ┆ 2.94  ┆ 33.4 │
│ 0.06905 ┆ 0.0  ┆ 2.18  ┆ 0    ┆ … ┆ 222 ┆ 18.7    ┆ 5.33  ┆ 36.2 │
└─────────┴──────┴───────┴──────┴───┴─────┴─────────┴───────┴──────┘

## Exploratory Data Analysis (EDA)

### Summary and Structure

In [21]:
print(Boston.shape)
print(Boston.schema)
print(Boston.describe())

(506, 13)
Schema({'crim': Float64, 'zn': Float64, 'indus': Float64, 'chas': Int64, 'nox': Float64, 'rm': Float64, 'age': Float64, 'dis': Float64, 'rad': Int64, 'tax': Int64, 'ptratio': Float64, 'lstat': Float64, 'medv': Float64})
shape: (9, 14)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ crim     ┆ zn        ┆ indus     ┆ … ┆ tax       ┆ ptratio   ┆ lstat     ┆ medv      │
│ ---       ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ f64      ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 506.0    ┆ 506.0     ┆ 506.0     ┆ … ┆ 506.0     ┆ 506.0     ┆ 506.0     ┆ 506.0     │
│ null_coun ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 3.613524 ┆ 11.363636 ┆ 11.136779 ┆ … ┆ 408.23715 ┆ 18.455534 ┆ 12.653063 ┆ 22.532806 │
│           ┆          ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆           │
│ std       ┆ 8.601545 ┆ 23.322453 ┆ 6.860353  ┆ … ┆ 168.53711 ┆ 2.164946  ┆ 7.141062  ┆ 9.197104  │
│           ┆          ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆           │
│ min       ┆ 0.00632  ┆ 0.0       ┆ 0.46      ┆ … ┆ 187.0     ┆ 12.6      ┆ 1.73      ┆ 5.0       │
│ 25%       ┆ 0.08199  ┆ 0.0       ┆ 5.19      ┆ … ┆ 279.0     ┆ 17.4      ┆ 6.93      ┆ 17.0      │
│ 50%       ┆ 0.25915  ┆ 0.0       ┆ 9.69      ┆ … ┆ 330.0     ┆ 19.1      ┆ 11.38     ┆ 21.2      │
│ 75%       ┆ 3.67822  ┆ 12.5      ┆ 18.1      ┆ … ┆ 666.0     ┆ 20.2      ┆ 16.96     ┆ 25.0      │
│ max       ┆ 88.9762  ┆ 100.0     ┆ 27.74     ┆ … ┆ 711.0     ┆ 22.0      ┆ 37.97     ┆ 50.0      │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Check for Nulls

In [22]:
Boston.select([
    pl.col(col).null_count().alias(col) for col in Boston.columns
    ])

shape: (1, 13)
┌──────┬─────┬───────┬──────┬───┬─────┬─────────┬───────┬──────┐
│ crim ┆ zn  ┆ indus ┆ chas ┆ … ┆ tax ┆ ptratio ┆ lstat ┆ medv │
│ ---  ┆ --- ┆ ---   ┆ ---  ┆   ┆ --- ┆ ---     ┆ ---   ┆ ---  │
│ u32  ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32 ┆ u32     ┆ u32   ┆ u32  │
╞══════╪═════╪═══════╪══════╪═══╪═════╪═════════╪═══════╪══════╡
│ 0    ┆ 0   ┆ 0     ┆ 0    ┆ … ┆ 0   ┆ 0       ┆ 0     ┆ 0    │
└──────┴─────┴───────┴──────┴───┴─────┴─────────┴───────┴──────┘

In [ ]:
# if there was a null, I would just fill it with the mean

## Train Model

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# split the data into train and test sets
y = Boston["medv"].to_numpy()
X = Boston.drop("medv").to_numpy()
columns = Boston.drop("medv").columns
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33,
                                                    random_state=7)
print("Split Dims:", X_train.shape, y_train.shape, X_test.shape, y_test.shape)

# train a linear regression model
reg = LinearRegression().fit(X_train, y_train)

# apply model
y_pred = reg.predict(X_test)

# print coefficients
coeff_df = pd.DataFrame(reg.coef_, columns=["Coefficient"], index=columns)
print(coeff_df)

# evaluate model
r2_train = reg.score(X_train, y_train)
mse_train = np.mean((reg.predict(X_train) - y_train)**2)
mae_train = np.mean(np.abs(reg.predict(X_train) - y_train))
print(f"Train - R2: {r2_train:.3f}, MSE: {mse_train:.3f}, MAE: {mae_train:.3f}")

r2_test = reg.score(X_test, y_test)
mse_test = np.mean((y_pred - y_test)**2)
mae_test = np.mean(np.abs(y_pred - y_test))
print(f"Test - R2: {r2_test:.3f}, MSE: {mse_test:.3f}, MAE: {mae_test:.3f}")

Split Dims: (339, 12) (339,) (167, 12) (167,)
         Coefficient
crim       -0.118031
zn          0.026491
indus       0.001952
chas        2.718967
nox       -16.080714
rm          5.172175
age        -0.010009
dis        -1.298121
rad         0.251450
tax        -0.011639
ptratio    -0.957838
lstat      -0.417936
Train - R2: 0.754, MSE: 21.806, MAE: 3.321
Test - R2: 0.659, MSE: 25.876, MAE: 3.410

/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/chethanjujjavarapu/Desktop/GitHub/ml-review/venv/lib/python3.13/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [ ]:
# build from scratch

import torch
import torch.nn.functional as F

class LinearRegression:

    def __init__(self, lr=1e-2, epochs=10, device=None):
        self.coef_ = None
        self.intercept_ = None
        self.lr = lr
        self.epochs = epochs
        self.mu = None
        self.sigma = None
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")

    def closed_form_fit(self, X, y):
        
        # z-score standardize
        X_standard = self._fit_standardizer(X)
        
        # add intercept
        ones_matrix = np.ones((X_standard.shape[0], 1))
        Xb = np.hstack((ones_matrix, X_standard))

        # get coefficients
        ## compute (Xb.T * Xb).-1
        theta_best = np.linalg.inv(Xb.T.dot(Xb))
        ## dot with Xb.T
        theta_best = theta_best.dot(Xb.T)
        ## dot with y
        theta_best = theta_best.dot(y)

        # store coefficients
        self.intercept_ = theta_best[0]
        self.coef_ = theta_best[1:]
    
    def _fit_standardizer(self, X):

        # get params
        self.mu = X.mean(axis=0, keepdims=True)
        sigma = X.std(axis=0, keepdims=True)
        sigma[sigma == 0.0] = 1.0  # guard against constant columns
        self.sigma = sigma
        
        # standardize
        X = (X - self.mu) / self.sigma

        return(X)
    
    def _apply_standardizer(self, X):

        return((X - self.mu)/self.sigma)

    def gradient_descent_fit(self, X, y, verbose=False):

        # setup

        # Ensure arrays with correct shapes/dtypes
        X = np.asarray(X, dtype=float) # (n x p)

        # standardize
        X_standard = self._fit_standardizer(X)

        # add intercept
        ones_matrix = np.ones((X_standard.shape[0], 1))
        Xb = np.hstack((ones_matrix, X_standard))

        y = np.asarray(y, dtype=float).reshape(-1, 1) # (n x 1)
        n_samples, n_features = X_standard.shape

        ## move to device
        Xb_t = torch.from_numpy(Xb).to(self.device)
        y_t  = torch.from_numpy(y).to(self.device)

        ## initialize weights (with intercept)
        weights = torch.zeros((n_features + 1, 1), dtype=Xb_t.dtype, device=self.device, requires_grad=True)

        # setup descent
        optimizer = torch.optim.SGD([weights], lr=self.lr)

        # ---- training loop (full-batch GD) ----
        for epoch in range(self.epochs):
            optimizer.zero_grad() # clear old gradients
            y_hat = torch.matmul(Xb_t, weights) # [n, 1] # get predictions
            loss = F.mse_loss(y_hat, y_t, reduction="mean")  # get mse error value
            loss.backward() # compute gradients
            optimizer.step() # update weights
            if verbose:
                print(f"epoch {epoch:5d} | mse {loss.item():.6f}")

        # convert back to numpy
        updated_weights = weights.detach().cpu().numpy().reshape(-1)
        self.intercept_ = float(updated_weights[0])
        self.coef_ = updated_weights[1:].copy()

    def predict(self, X):

        # standardize
        X_standard = self._apply_standardizer(X)

        # add intercept
        ones = np.ones((X_standard.shape[0], 1))
        Xb = np.hstack((ones, X_standard))

        # make predictions
        weights = np.concatenate(([self.intercept_], self.coef_), axis=None)
        return Xb.dot(weights) # (n x p) x (p x 1) = n
    
    def r2_score(self, X, y):

        tss = np.sum(np.square(y - np.mean(y)), axis=None)
        rss = np.sum(np.square(y - self.predict(X)), axis=None)
        return ((tss - rss) / tss)
    
    def mae_score(self, X, y):
        deltas = y - self.predict(X)
        absolute_deltas = np.abs(deltas)
        n = absolute_deltas.shape[0]
        return(np.sum(absolute_deltas, axis=None)/n)

    def mse_score(self, X, y):

        deltas = y - self.predict(X)
        squared_deltas = np.square(deltas)
        n = squared_deltas.shape[0]
        return(np.sum(squared_deltas, axis=None)/n)

In [54]:
# train a linear regression model using gradient descent
reg = LinearRegression(epochs=10000)
reg.gradient_descent_fit(X_train, y_train, verbose=False)

# apply model
y_train_pred = reg.predict(X_train)
y_pred = reg.predict(X_test)

# print coefficients
coeff_df = pd.DataFrame(reg.coef_, columns=["Coefficient"], index=columns)
print(coeff_df)

# evaluate model

## r2, mse, mae
print("")
print("Train")
print("R2:", reg.r2_score(X_train, y_train))
print("MAE:", reg.mae_score(X_train, y_train))
print("MSE:", reg.mse_score(X_train, y_train))
print("")
print("Test")
print("R2:", reg.r2_score(X_test, y_test))
print("MAE:", reg.mae_score(X_test, y_test))
print("MSE:", reg.mse_score(X_test, y_test))

         Coefficient
crim       -0.850048
zn          0.608635
indus       0.013570
chas        0.710623
nox        -1.823572
rm          3.741180
age        -0.279976
dis        -2.721345
rad         2.138363
tax        -1.937357
ptratio    -2.090053
lstat      -3.062995

Train
R2: 0.7538411248592943
MAE: 3.320553802560455
MSE: 21.80643140396327

Test
R2: 0.6590081342000099
MAE: 3.409733644990937
MSE: 25.876334203450607

In [53]:
# train a linear regression model using closed form
reg = LinearRegression()
reg.closed_form_fit(X_train, y_train)

# apply model
y_train_pred = reg.predict(X_train)
y_pred = reg.predict(X_test)

# print coefficients
coeff_df = pd.DataFrame(reg.coef_, columns=["Coefficient"], index=columns)
print(coeff_df)

# evaluate model

## r2, mse, mae
print("")
print("Train")
print("R2:", reg.r2_score(X_train, y_train))
print("MAE:", reg.mae_score(X_train, y_train))
print("MSE:", reg.mse_score(X_train, y_train))
print("")
print("Test")
print("R2:", reg.r2_score(X_test, y_test))
print("MAE:", reg.mae_score(X_test, y_test))
print("MSE:", reg.mse_score(X_test, y_test))

         Coefficient
crim       -0.850048
zn          0.608635
indus       0.013570
chas        0.710623
nox        -1.823572
rm          3.741180
age        -0.279976
dis        -2.721345
rad         2.138364
tax        -1.937358
ptratio    -2.090053
lstat      -3.062995

Train
R2: 0.7538411248592968
MAE: 3.3205538249911606
MSE: 21.806431403963053

Test
R2: 0.659008140551209
MAE: 3.4097336094727675
MSE: 25.876333721486763

In [50]:
# so, a given coefficient value means that the median house values changes by that coefficient for every 1 standard deviation increase in that feature while holding all other features constant.